/* @flow */
const GET_ITEM_BEGIN: 'GET_ITEM_BEGIN' = 'GET_ITEM_BEGIN';
const GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS' = 'GET_ITEM_SUCCESS';
const GET_ITEM_FAILURE: 'GET_ITEM_FAILURE' = 'GET_ITEM_FAILURE';

const ADD_ITEM_BEGIN: 'ADD_ITEM_BEGIN' = 'ADD_ITEM_BEGIN';
const ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS' = 'ADD_ITEM_SUCCESS';
const ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE' = 'ADD_ITEM_FAILURE';

const EDIT_ITEM_BEGIN: 'EDIT_ITEM_BEGIN' = 'EDIT_ITEM_BEGIN';
const EDIT_ITEM_SUCCESS: 'EDIT_ITEM_SUCCESS' = 'EDIT_ITEM_SUCCESS';
const EDIT_ITEM_FAILURE: 'EDIT_ITEM_FAILURE' = 'EDIT_ITEM_FAILURE';

const DELETE_ITEM_BEGIN: 'DELETE_ITEM_BEGIN' = 'DELETE_ITEM_BEGIN';
const DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS' = 'DELETE_ITEM_SUCCESS';
const DELETE_ITEM_FAILURE: 'DELETE_ITEM_FAILURE' = 'DELETE_ITEM_FAILURE';

const LIST_ITEMS_BEGIN: 'LIST_ITEMS_BEGIN' = 'LIST_ITEMS_BEGIN';
const LIST_ITEMS_SUCCESS: 'LIST_ITEMS_SUCCESS' = 'LIST_ITEMS_SUCCESS';
const LIST_ITEMS_FAILURE: 'LIST_ITEMS_FAILURE' = 'LIST_ITEMS_FAILURE';

export {
  GET_ITEM_BEGIN,
  GET_ITEM_SUCCESS,
  GET_ITEM_FAILURE,
  ADD_ITEM_BEGIN,
  ADD_ITEM_SUCCESS,
  ADD_ITEM_FAILURE,
  EDIT_ITEM_BEGIN,
  EDIT_ITEM_SUCCESS,
  EDIT_ITEM_FAILURE,
  DELETE_ITEM_BEGIN,
  DELETE_ITEM_SUCCESS,
  DELETE_ITEM_FAILURE,
  LIST_ITEMS_BEGIN,
  LIST_ITEMS_SUCCESS,
  LIST_ITEMS_FAILURE,
};
